config/routes.rb
Rails.application.routes.draw do
  resources :employment_centers
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  post 'upload', to: 'employment_centers#upload'
  post 'find', to: 'employment_centers#find'
  get  'find', to: 'employment_centers#index'

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'dashboard#index'
  root 'dashboard#index'
end

app/models/employment_center.rb
class EmploymentCenter < ApplicationRecord
  YEAR  = Time.now.year.to_s.freeze
  MONTH = Time.now.month.to_s.freeze
  TIME  = Time.now.strftime('%d-%m-%Y_%H:%M').freeze

  class << self
    def current_user
      Thread.current[:user]
    end

    def current_user=(user)
      Thread.current[:user] = user
    end

    def parse_document(dbf)
      data = DBF::Table.new(StringIO.new(dbf))
      data_hash = {}
      data.map { |row| data_hash[data_hash.size + 1] = encode(row) }
      data_hash
    end

    def find_user(user)
      fm = user.split.first
      users = {}
      Dir["#{current_folder}/*"].each do |file|
        file_name = file.split('/').last
        next unless file_name.start_with? 'resp'
        file = File.read(file)
        users[file_name] = YAML.load(file).select { |_, v| v['FM'].casecmp(fm).zero? }
      end
      users.reject { |_, v| v.empty? }
    end

    def create_structure_folders(file)
      create_user_root_folder
      create_year
      create_month
      file = "#{file.original_filename.split('.').first}_#{TIME}.yml"
      Rails.root.join('public', current_user.email, YEAR, MONTH, file)
    end

    private

    def encode(data)
      Hash[data.attributes.map { |k, v| [k, v.force_encoding('cp866').encode('utf-8')] }]
    end

    def current_folder
      Rails.root.join('public', current_user.email, YEAR, MONTH)
    end

    def create_user_root_folder
      check_dir(Rails.root.join('public', current_user.email))
    end

    def create_year
      check_dir(Rails.root.join('public', current_user.email, YEAR))
    end

    def create_month
      check_dir(Rails.root.join('public', current_user.email, YEAR, MONTH))
    end

    def check_dir(dir)
      Dir.mkdir(dir) unless Dir.exist? dir
    end
  end
end

app/controllers/employment_centers_controller.rb
class EmploymentCentersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :check_files, only: [:upload]
  before_action :check_user, only: [:find]
  before_action :set_current_user, only: [:upload, :find]

  def index
  end

  def find
    @users = EmploymentCenter.find_user(employment_centers_params[:user])
    if @users.empty?
      flash[:notice] = 'Человек не найден, возможно он не стоит на учете'
      redirect_to employment_centers_path
    end
  end

  def upload
    params[:files].each do |file|
      folder = EmploymentCenter.create_structure_folders(file)
      File.open(folder, 'wb') do |new_file|
        new_file.write(YAML.dump(EmploymentCenter.parse_document(file.read)))
      end
    end
    flash[:notice] = 'Документ успешно загружен'
    redirect_to employment_centers_path
  end

  private

  def employment_centers_params
    params.require(:employment_centers).permit(:user)
  end

  def check_files
    unless params.include? :files
      flash[:notice] = 'Произошла ошибка, попробуйте снова'
      redirect_to new_employment_center_path
    end
  end

  def check_user
    if employment_centers_params[:user].empty?
      @users = {}
      flash[:notice] = 'Человек не найден, возможно он не стоит на учете'
      redirect_to employment_centers_path
    end
  end

  def set_current_user
    EmploymentCenter.current_user = current_user
  end
end

app/helpers/employment_centers_helper.rb
module EmploymentCentersHelper
  def total_amount(user)
    user.select { |k, _| k.start_with? 'SUM' }.values.map(&:to_f).sum.round(2)
  end

  def table_money_monthly(user, date)
    half_year = get_last_half_year(date)
    money_monthly = user.select { |k| k.start_with? 'SUM' }.values.map(&:to_f)
    content_tag(:table, 'class' => 'table') do
      output = ''
      output += content_tag(:tr)
      half_year.map { |month| output += content_tag(:th, month) }
      output += content_tag(:tr)
      money_monthly.map { |sum| output += content_tag(:td, sum) }
      output.html_safe
    end
  end

  def print_spravka(user)
    "print_spravka(#{user['NUMK'].split('/').first})"
  end

  def get_last_half_year(date)
    months = %w(Январь Февраль Март Апрель Май Июнь Июль
                Август Сентябрь Октябрь Ноябрь Декабрь)
    month = Date.parse(date).month
    first_month = month - 6
    if first_month.positive?
      months[month - 6..month - 1]
    else
      months.last(6 - first_month.abs) + months.first(first_month.abs)
    end
  end
end

app/views/employment_centers/_form.html.erb
<div class="actions">
  <%= form_tag upload_path, multipart: true do %>
    <%= file_field_tag 'files[]', multiple: true %>
    <%= submit_tag 'Загрузить' %>
  <% end %>
</div>

app/views/employment_centers/edit.html.erb
<h1>Editing Employment Center</h1>

<%= render 'form', employment_center: @employment_center %>

<%= link_to 'Show', @employment_center %> |
<%= link_to 'Back', employment_centers_path %>

app/views/employment_centers/find.html.erb
<p id="notice"><%= notice %></p>
<table class="table">
  <tr>
    <th>Файл ответа</th><th>Фамилия</th> <th>Имя</th><th>Отчетсво</th> <th>День Рождения</th><th>Адрес</th>
  </tr>
  <% @users.each_pair do |k, v| %>
    <% v.each_value do |user| %>
      <tr>
      <td><%= k.split('_')[1] %></td>
      <td><%= user['FM'] %></td>
      <td><%= user['IM'] %></td>
      <td><%= user['OT'] %></td>
      <td><%= user['BIR'] %></td>
      <td><%= user['AD'] %></td>
      <td><%= button_tag 'Распечатать справку', class: "btn btn-default", onclick: print_spravka(user) %></td>
      </tr>
      <td class="collapse" id=<%= user['NUMK'].split('/').first %> >
        <%= render 'layouts/spravka_bezrab', user: user, date: k.split('_')[1] %>
      </td>
    <% end %>
  <% end %>
</table>
<br>
<br>
<%= link_to 'Назад', employment_centers_path %>

app/views/employment_centers/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="header_text">Сделайте поиск нужного человека или загрузите ответ с центра занятости</h2>
<%= form_tag find_path do %>
  <div class="input-group">
    <%= text_field_tag 'employment_centers[user]', nil, placeholder: "Введите ФИО...", class: "form-control" %>  
    <span class="input-group-btn">
      <button class="btn btn-default" type="submit">Искать!</button>
    </span>
  </div>
<% end %>    

<br>
<br>
<%= link_to 'Загрузить файлы', new_employment_center_path %>

app/views/employment_centers/new.html.erb
<h2>Загрузка файлов ЦЗН</h2>

<%= render 'form', employment_center: @employment_center %>

<%= link_to 'Назад', employment_centers_path %>

app/views/employment_centers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_employment_center_path(@employment_center) %> |
<%= link_to 'Back', employment_centers_path %>