config/routes.rb
Rails.application.routes.draw do
  resources :employment_centers
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  post 'upload', to: 'employment_centers#upload'
  post 'find', to: 'employment_centers#find'
  get  'find', to: 'employment_centers#index'

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'dashboard#index'
  root 'dashboard#index'
end

app/views/layouts/_nav_left.html.erb
<div class="nav_left">
  <nav class="navbar-default navbar-side" role="navigation">
    <div class="sidebar-collapse">
      <ul class="nav" id="main-menu">
        <li><%= link_to "Центр занятости", employment_centers_path, class: "active-menu" %></li>
        <li><%= link_to "Монитор VPN", root_path, class: "active-menu" %></li>
        <li><%= link_to "Монитор точка интеграции", root_path, class: "active-menu" %></li>
        <li><%= link_to "Монитор мультишлюз", root_path, class: "active-menu" %></li>
      </ul>
     </div>
  </nav>
</div>

app/views/layouts/_nav_top.html.erb
<nav class="navbar navbar-default navbar-cls-top header" role="navigation" style="margin-bottom: 0">
    <%= link_to 'Веб-сервисы ГКУ "КЦСЗН" Забайкальского края', root_path , class: 'navbar-brand' %>

  <ul class="nav navbar-nav navbar-right">
    <% if current_user %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <div id="user_email"><span class="link-sign_in"><%= current_user.email %></span><b class="caret"></div></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="blog.html">BLOG</a></li>
          <li><a href="single-post.html">SINGLE POST</a></li>
          <li><a href="portfolio.html">PORTFOLIO</a></li>
          <li><%= link_to 'Выйти', sign_out_path %></li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to 'Войти', sign_in_path, class: "link-sign_in" %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/_spravka_bezrab.html.erb
<div>
  <center>
    <p class="center">СПРАВКА № <%= user['NUMK'] %></p>                        
    <p class="center">По состоянию на <%= date %></p>
  </center>
  <br>
  <br>
<p><%= "#{user['FM']} #{user['IM']} #{user['OT']}" %></p>
<p>Адрес регистрации: <%= user['AD'] %></p>   
        
<p>в соответствии с законодательством о занятости населения в Российской Федерации с  04.03.2009</p>      
<p>состоял(а) на учете в ГУ "Центр занятости населения города Читы"</p>                 
                  
<p>Продолжает состоять на учете<p>                 
                  
<p>Вид выплаты - пособие по безработице<p>            
                  
<p>Сумма начисленных выплат за последние шесть месяцев составляет: <%= total_amount(user) %><p>  

<%= table_money_monthly(user, date) %>    
          
<p>Основание: файл выгрузки базы данных центра занятости населения от <%= date %></p>                  
                  
<p>И.О.руководителя</p>                  
<p>"Государственной службы занятости населения Забайкальского края"      ЭЦП верна   Щеглова И.С.</p>        
<p>(подпись)   (Ф.И.О.)</p>        
                  
<p>Главный инспектор отдела автоматизации ГКУ "КЦСЗН" Забайкальского края      ЭЦП верна   Горбачёв А.А.</p><br>       
<p style="text-align: right;text-decoration: overline;">(подпись)   (Ф.И.О.)</p>
                  
<p>Справка соответствует электронному документу</p><br>                  
<p style="text-align: right;text-decoration: overline;">(подпись)   (Ф.И.О. специалиста филиала ЕСРЦ)</p>       
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebKcszn</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav_top' %>
    <%= render 'layouts/nav_left' %>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>